### PR TITLE
Add function implemented. 

### PR DESCRIPTION
**Pull request by ConeRX**
Now with right version.

### CODE REVIEW

**Comment by mario-kr** [comment]
Sorry, but not usable. Also, we already got this functionality.

**Comment by ConeRX** [comment]
Ok, but I don't see it anywhere?

**Comment by mario-kr** [comment]
task::into_filelockentry();
It's a Trait implemented for task_hookrs::task::Task
The usage of this is implemented in imag-todo/src/main.rs on my branch "impl_ui", which i will merge tomorrow when i finish.

**Comment by matthiasbeyer** [comment]
@mario-kr As this PR goes also against your `imag-task` branch I think I can comment here.

Please close this unmerged, it
1. is outdated and therefor not mergeable
2. misses the point of the whole crate

Thanks.

**Pull request closed without merging**
